version: "3.9"

services:
  frontend:
    image: fr172m/frontend:v0.2
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    image: fr172m/backend:v0.2
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      - db
      - sandbox
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 10s





  db:
    image: fr172m/db:v0.2
    env_file:
      - .env.docker
    ports:
      - "5432:5432"

  sandbox:
    image: fr172m/sandbox:v0.2
