version: "3.9"

networks:
  vr-network:
    driver: bridge

services:
  frontend:
    container_name: frontend
    image: vr-robot-app/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - vr-network

  backend:
    container_name: backend
    image: vr-robot-app/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ${PWD}/sandboxRun:/sandboxRun
    networks:
      - vr-network
    env_file:
      - .env.docker

  db:
    container_name: db
    image: vr-robot-app/db:latest     # HIER: eigenes Image
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.docker
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - vr-network


  sandbox:
    container_name: sandbox
    build:
      context: ./sandbox
      dockerfile: Dockerfile
    image: vr-robot-app/sandbox:latest
    networks:
      - vr-network
    ports:
      - "5000:5000"                        # z.B. HTTP-API Port



volumes:
  db_data:
  sandbox_data:
